### ISSUE TITLE
Paypal Data Collector com.paypal.android.sdk:data-collector: Consider upgrading to version com.braintreepayments.api:data-collector:3.21.0 of the SDK.

### ISSUE THREAD

**Issue by BunnyBuddy** [pikaju/flutter-braintree#150]
Hi, we've been using the package for a long time and a few days ago we got the warning from PlayStore,

![Screenshot 2024-02-19 at 1 08 03 PM](https://github.com/pikaju/flutter-braintree/assets/18241925/731383fe-c00c-4e4b-830f-11730a278820)

![Screenshot 2024-02-19 at 1 08 37 PM](https://github.com/pikaju/flutter-braintree/assets/18241925/bd2ecaa4-797e-4131-858d-1e85084575d1)

Can someone tell me how to resolve this?

**Comment by claudius-kienle** [comment]
The reason for this warning is that this package uses an old version of 'com.braintreepayments.api:drop-in'.

For me, it was enough to just update the version of this package to '6.13.0'.

The package with an updated version of 'com.braintreepayments.api:drop-in' can be found at https://github.com/claudius-kienle/flutter-braintree and one can overwrite this dependency in the pubspec.yaml by adding a entry to `dependency_overrides`:

```yaml
...
dependency_overrides:
  flutter_braintree:
    git: 
      url: https://github.com/claudius-kienle/flutter-braintree.git
      ref: 053a19e
```
